### ISSUE TITLE
ki --watch #macros

### ISSUE THREAD

**Issue by orlin** [lantiga/ki#21]
The `--watch` option does not work for `ki macro`.  And the `--include`d code doesn't get watched at all.  I ended up writing a little [gulpfile.js](https://github.com/datomicon/datomiki/blob/active/gulpfile.js), so I'd be able to play with macros.  I imagine someone may write a gulp-ki plugin some day...  Though this is just a few lines good-enough copy/paste fix that does the job.

**Comment by lantiga** [comment]
I've fixed the ki command to also watch for changes in macros in the source file as well as included files. Since changing macros is more expensive than compiling, sweet is reinvoked only if macros actually change in their content.
