### ISSUE TITLE
ki exit code

### ISSUE THREAD

**Issue by orlin** [lantiga/ki#22]
The exit code of the `ki` command should be `1` (or non-`0`) when there are errors.  This way one could use tools such as [gulp-notify](https://www.npmjs.com/package/gulp-notify) or [nanybar](https://github.com/rumpl/nanybar) to get notified about compilation status.

**Comment by lantiga** [comment]
Good idea, done. It's in master, I haven't released yet. I'll take a look at the other issues first.
