### ISSUE TITLE
ki --autonomous #error

### ISSUE THREAD

**Issue by orlin** [lantiga/ki#24]
It gives me a `SyntaxError: Unexpected token ;`

```
r("mori.mutable.disj.fn",ge.K);;return this.mori;}.call({});});
                                                           ^
```

**Comment by lantiga** [comment]
Can you share a snippet that reproduces the error? It's working for me.

**Comment by orlin** [comment]
I pushed a [datomiki ki-a-mori branch](https://github.com/datomicon/datomiki/tree/ki-a-mori) to point to the commit where I realized it wasn't working.  First I thought it was a problem because I had ki `npm link`-ed and forgot to `npm install`, but it builds without errors.  Do `npm run build` to confirm.  Running `node datomiki.js` produces:

```
/Users/om/Dev/datomiki/datomiki.js:924
disj.f2",ge.a);r("mori.mutable.disj.fn",ge.K);;return this.mori;}.call({});});
                                                                          ^
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:427:25)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
    at Function.Module._load (module.js:294:12)
    at Function.Module.runMain (module.js:485:10)
    at startup (node.js:112:16)
    at node.js:863:3
```

I get the same error with node 0.10, 0.12, and io.js - it otherwise runs fine on all three.

**Comment by orlin** [comment]
I ran into an npm bug - if mori is a devDependency of a project that has ki as dependency, npm doesn't install  `node_modules/ki/node_modules/mori` and ki can't can't build with `--autonomous` option because mori isn't found where expected.  Getting around this didn't fix the issue.

**Comment by lantiga** [comment]
Sorry for the wait, I couldn't reproduce the error until I noticed that you were using source maps: the error showed only when -a was used in conjunction with -s. It's fixed now in master, I'll release shortly.
