### ISSUE TITLE
+ does not work

### ISSUE THREAD

**Issue by stammi** [lantiga/ki#31]
```
ki require core

return ki(+ 2 3);
```

returns 3.

See also: 
http://ki-lang.org/editor/editor.html#ki%20require%20core%0A%0Areturn%20ki%28+%202%203%29;

**Comment by lantiga** [comment]
Operations are (add 2 3) etc (see docs)
Alternatively you can use (js 2 + 3)

**Comment by stammi** [comment]
Thanks, Sorry for not to rtfm.

Should this at least be an error of some kind? It can introduce quite subtle bugs.

**Comment by lantiga** [comment]
Yes, absolutely. Mind opening an issue? Thanks!
